
# fuente consulta: https://youtu.be/uqBZEL9m2V4?si=hR-HnuHl_5HsNtPS
## CODIGO FUENTE: https://github.com/pedrovelasquez9/springboot-postgresql-docker-compose.git

#FROM openjdk:17-jdk-alpine
FROM openjdk:17

RUN mkdir -p /home/app

COPY /app-java/dev1/target/dockerized.postgresql-0.0.1-SNAPSHOT.jar /home/app/java-app.jar

WORKDIR /home/app
COPY /app-java/dev1/ .

#EXPOSE 8080

ENTRYPOINT ["java", "-jar", "java-app.jar"]