FROM openjdk:17

RUN mkdir -p /home/app

COPY /target/dockerized.postgresql-0.0.1-SNAPSHOT.jar /home/app/java-app.jar

WORKDIR /home/app
COPY . .

#EXPOSE 8080

ENTRYPOINT ["java", "-jar", "java-app.jar"]